###################################################[DRUGS v6.1]########################################################

# DISCLAIMER: EDIT AT YOUR OWN RISK! IMPROPER USE OF CONFIG MAY RESULT IN CRASHES.
 # If after editing the config you experience issues, delete the file and restart the server...

# --------------------------------------------[USAGE RECIPE TOGGLE]----------------------------------------------------

# Allows administrators to toggle usage of individual drugs.

# Toggle message sent to players informing them the drugs they are attempting to take are disabled.
drugMessage:
  enabled: true

NarcanUse:
  enabled: true
CocaineUse:
  enabled: true
HeroinUse:
  enabled: true
AdderallUse:
  enabled: true
SteroidsUse:
  enabled: true
HennessyUse:
  enabled: true
KetamineUse:
  enabled: true
MarijuanaUse:
  enabled: true
LSDUse:
  enabled: true
EcstasyUse:
  enabled: true
AyahuascaUse:
  enabled: true
ShroomsUse:
  enabled: true

# --------------------------------------------[DRUG RECIPE TOGGLE]-----------------------------------------------------

# Allows administrators to toggle individual crafting recipes.

# Toggle all recipes server-wide for all players.
allRecipes:
  enabled: true

# Toggle individual recipes server-wide for all players.
NarcanRecipe:
  enabled: true
CocaineRecipe:
  enabled: true
HeroinRecipe:
  enabled: true
AdderallRecipe:
  enabled: true
SteroidsRecipe:
  enabled: true
HennessyRecipe:
  enabled: true
KetamineRecipe:
  enabled: true
MarijuanaRecipe:
  enabled: true
LSDRecipe:
  enabled: true
EcstasyRecipe:
  enabled: true
AyahuascaRecipe:
  enabled: true
ShroomsRecipe:
  enabled: true

# -------------------------------------------[TRANSLATION SECTION]-----------------------------------------------------

# It is recommended that you DO NOT edit the following section. It is intended for language translation only.
  # Make sure ALL FIELDS are filled, or plugin may not function properly.
  # DISCLAIMER: Edits to this section may result in formatting issues.
  # '§' is the symbol to denote color codes in messages.

#DrugCommandExecutor
verifyPermission: "§cYou do not have the required permissions to run this command."
verifyDrug: "§cPlease select a valid drug."
announceDrug: "§2You spawned "
selectDrug: "§c§lPlease select one of the following drugs:"
usageMessage: "§2Usage: §6/drugs <drug>§2 to spawn."

#DrugsItems
narcanMessage: "§2Removes all §6drug §2and §6withdrawal §2effects."
messageStartPsych: "§2Grants §6" # [effect name]
messageEndPsych: "§2 for two minutes."
useInstructionPsych: "§2SHIFT CLICK to use."

#NarcanListner
milkMessage: "§cYou must use Narcan to cancel the effects of drugs..."
consumeNarcan: "§2Your mind feels clear now..."

#PsychoactiveDrugListener
verifyUsage: "§cYou must SHIFT + RIGHT-CLICK to consume drugs..."
drugPermission: "§cYou do not have the required permissions to take drugs."
drugDisabled: "§cThis drug is disabled."
consumeStart: "§2§lYou took §6§l" # [drug name]
consumeMiddle: " §2§land " # [effect message]
consumeEnd: " for §6§l2 minutes§2§l!"
passingMessage: "§cI feel like passing out..."
overdoseMessage: "§cYou overdosed and died..."
dizzyMessage: "§c§oUh oh, I don't feel so good..."
withdrawalMessageStart: "§2§lYou're suffering from §6§lwithdrawal §2§land " # [withdrawal effect message]
withdrawalMessageEnd: " §2§lfor §6§l30 seconds§2§l..."
